# Generated by Django 4.2.2 on 2023-06-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/img/Certificate/')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('about', models.TextField()),
            ],
        ),
    ]
