# Generated by Django 4.2.2 on 2023-06-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0003_remove_home_about_images_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/img/services/')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
            ],
        ),
    ]
