# Generated by Django 4.2.2 on 2023-06-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0004_home_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(max_length=250)),
            ],
        ),
    ]
