# Generated by Django 4.2.2 on 2023-06-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0009_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('full_name', models.CharField(max_length=60)),
                ('jobs_name', models.CharField(max_length=40)),
            ],
        ),
    ]
