# Generated by Django 4.2.2 on 2023-06-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0011_home_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_images', models.ImageField(upload_to='images/product/img/')),
                ('title', models.CharField(max_length=46)),
                ('price', models.IntegerField()),
                ('text', models.TextField()),
                ('phone_numbers', models.CharField(default=675, max_length=250)),
            ],
        ),
    ]
